//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public int Book_Id { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        public string Author { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        public Nullable<int> Price { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        public string Title { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        [Display(Name = "Number of copies")]
        public Nullable<int> Number_of_Copies { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        public string Category { get; set; }
        public Nullable<int> Issue_Admin_Id { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        [Display(Name = "Arrival Date")]
        public Nullable<System.DateTime> Arrival_Date { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
