//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Issues = new HashSet<Issue>();
            this.monitors = new HashSet<monitor>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        public string AustId { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        [Display(Name = "Username")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        [DataType(DataType.Password)]
        [Display(Name = "Re-enter Password")]
        [Compare("Password", ErrorMessage = "Confirm password doesn't match!")]
        public string RePassword { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        [Display(Name = "Phone number")]
        public string Phone_Number { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "This field can not be empty!")]
        public Nullable<System.DateTime> JoiningDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Issue> Issues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<monitor> monitors { get; set; }
    }
}
