//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class monitor
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Arrival_time { get; set; }
        public Nullable<System.DateTime> Exit_Time { get; set; }
        public Nullable<int> Admin_Id { get; set; }
        public Nullable<int> Member_Id { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Member Member { get; set; }
    }
}
