//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reutrn
    {
        public int Return_Id { get; set; }
        public Nullable<System.DateTime> Approve_Time { get; set; }
        public Nullable<int> Admin_Id { get; set; }
        public Nullable<int> Issue_Id { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Issue Issue { get; set; }
    }
}
